"""add gallery table

Revision ID: 0e7ed53385df
Revises: c37581271f5e
Create Date: 2024-04-05 00:53:58.796453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7ed53385df'
down_revision = 'c37581271f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
