"""updated table

Revision ID: 36c159e9bc65
Revises: c0aa51829d07
Create Date: 2024-05-06 11:09:07.324840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c159e9bc65'
down_revision = 'c0aa51829d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
