"""changed contact data type to string

Revision ID: 380c494a2d57
Revises: b316d6a53150
Create Date: 2024-04-04 09:59:18.932950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380c494a2d57'
down_revision = 'b316d6a53150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
