"""add read column in notification

Revision ID: 546366424d8f
Revises: 79523a8ea860
Create Date: 2024-06-08 22:06:30.061644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546366424d8f'
down_revision = '79523a8ea860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('super_admin_read', sa.Boolean(), nullable=True))
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('super_admin_read')
        batch_op.drop_column('admin_read')
        batch_op.drop_column('seller_read')

    # ### end Alembic commands ###
