"""removed nullable in customer table 

Revision ID: 6bf089f0343d
Revises: 1a066596acf1
Create Date: 2024-04-10 16:17:36.841491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf089f0343d'
down_revision = '1a066596acf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
