"""add read column in notification

Revision ID: 79523a8ea860
Revises: c411d29438db
Create Date: 2024-06-08 21:47:02.103228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79523a8ea860'
down_revision = 'c411d29438db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
