"""Add seller id in customer table

Revision ID: 88034a76e30c
Revises: 0e7ed53385df
Create Date: 2024-04-08 10:56:25.491244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88034a76e30c'
down_revision = '0e7ed53385df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_customers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customer_seller_id', 'user', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_seller_id', type_='foreignkey')
        batch_op.drop_column('seller_id')

    op.create_table('_alembic_tmp_customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name='fk_customer_seller_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
