"""Add user, inventory and importation table

Revision ID: 8e9e1ae19bbf
Revises: 
Create Date: 2024-03-28 22:07:22.720492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9e1ae19bbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('VIN', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('body_style', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('engine_size', sa.String(), nullable=False),
    sa.Column('drive_type', sa.String(), nullable=False),
    sa.Column('trim_level', sa.String(), nullable=False),
    sa.Column('gallery', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('cylinder', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('stock_number', sa.Integer(), nullable=False),
    sa.Column('purchase_cost', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_of_origin', sa.String(), nullable=False),
    sa.Column('transport_fee', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('import_duty', sa.String(), nullable=False),
    sa.Column('import_date', sa.String(), nullable=False),
    sa.Column('import_document', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importations')
    op.drop_table('inventories')
    op.drop_table('user')
    # ### end Alembic commands ###
